---
title: "Untitled"
output: html_document
date: "2025-10-15"
---

```{r}
library(dplyr)
library(tidyr)
library(slider)
library(lubridate)
library(ggplot2)
library(stringr)
library(stringi)
library(fuzzyjoin)
library(tibble)
library(purrr)
library(stats)


setwd('/users/coop/desktop/hoops')
```

```{r}
tagged <- read.csv('tagged_shots.csv')

game_log <- read.csv('game_log.csv')
game_log$date <- mdy(game_log$date)
```

```{r}
team_pct_game <- tagged %>%
  left_join(game_log %>% select(game_id, date), by = "game_id") %>%
  group_by(opp, game_id, date, zone) %>%
  summarise(
    att   = n(),
    makes = sum(make, na.rm = TRUE),
    pct   = ifelse(att > 0, makes / att, NA_real_),
    .groups = "drop"
  )

player_pct_game <- tagged %>%
  left_join(game_log %>% select(game_id, date), by = "game_id") %>%
  group_by(shooter, game_id, date, zone) %>%
  summarise(
    att   = n(),
    makes = sum(make, na.rm = TRUE),
    pct   = ifelse(att > 0, makes / att, NA_real_),
    .groups = "drop"
  )
```

```{r}
zone_mean <- tagged %>% 
  group_by(zone) %>% 
  summarise(mean = sum(make) / n())
```

```{r}
team_long <- team_pct_game %>%
  group_by(opp, zone) %>%
  arrange(date, game_id, .by_group = TRUE) %>%
  mutate(
    allow_pct_prev10 =
      slide_dbl(lag(pct), ~ mean(.x, na.rm = TRUE), .before = 10 - 1, .complete = TRUE)
) %>%
  ungroup() %>% 
  right_join(zone_mean, by = "zone") %>%
  mutate(diff_d = mean - allow_pct_prev10) %>% 
  select(-mean)


```

```{r}
player_long <- player_pct_game %>%
  group_by(shooter, zone) %>%
  arrange(date, game_id, .by_group = TRUE) %>%
  mutate(
    pct_prev10 =
      slide_dbl(lag(pct), ~ mean(.x, na.rm = TRUE), .before = 10 - 1, .complete = TRUE),
    shots_prev10 =
      slide_dbl(lag(att), ~ sum(.x, na.rm = TRUE), .before = 10 - 1, .complete = TRUE)
) %>%
  ungroup() %>% 
  right_join(zone_mean, by = "zone") %>%
  mutate(diff = pct_prev10 - mean) %>% 
  select(-mean)

player_long <- tagged %>% 
  select(shooter, game_id, team, opp) %>% 
  unique() %>% 
  right_join(player_long, by = c('shooter', 'game_id'))
```

```{r}
matchups <- team_long %>% 
  select(opp, game_id, zone, diff_d) %>% 
  right_join(player_long, by = c('opp', 'game_id', 'zone')) %>% 
  mutate(diff_gap = diff - diff_d,
         abs_gap = abs(diff_gap))

matchups %>% filter(shooter == "Trae Young") %>% 
  write.csv('trae_sample.csv', row.names = F)
```

```{r}
matchups_game <- matchups %>%
  mutate(w = coalesce(shots_prev10, 0)) %>%                 # last-10 volume by zone
  filter(!is.na(diff_gap)) %>%                              # need a gap to score
  group_by(shooter, team, opp, game_id, date) %>%
  summarise(
    w_sum      = sum(w, na.rm = TRUE),
    w_diff_gap = ifelse(
      w_sum > 0,
      sum(diff_gap * w, na.rm = TRUE) / w_sum,             # weighted by last-10 mix
      mean(diff_gap, na.rm = TRUE)                         # fallback if no last-10 shots
    ),
    zones_used = n_distinct(zone[w > 0 & !is.na(diff_gap)]),
    .groups = "drop"
  )

```

```{r}

matchups_filt1 <- matchups_game %>% 
  filter(zones_used > 3)

```

```{r}

ggplot(matchups_filt1, aes(x = w_sum))+
  geom_histogram()

```

```{r}
bs <- read.csv('rolled_basic.csv')


```

```{r}

bs$player <- gsub("Bogdan Bogdanović ", "Bogdan Bogdanović",
bs$player)

```

```{r}
shot_chart_uni <- tagged %>% 
  select(shooter) %>% 
  unique()

box_score_uni <- bs %>% 
  select(player) %>% 
  unique()
```

```{r}
bs <- read.csv('/Users/cooperfoster/Desktop/hoops/rolled_basic.csv')
```

```{r}

bs <- bs %>% 
  left_join(game_log %>% select(game_id, date), by = "game_id")

```

```{r}

bs$pts <- as.numeric(bs$pts)

shooter_ppg10 <- bs %>% 
  group_by(player) %>% 
  arrange(date, game_id, .by_group = T) %>% 
  mutate(
    ppg_prev10 = 
      slide_dbl(lag(pts), ~mean(.x, na.rm = T), .before = 10 - 1, .complete = T)
  ) %>% 
  ungroup() %>% 
  select(game_id, team_code, player, pts, ppg_prev10)


```

```{r}
tagged_players <- tagged %>% 
  select(shooter) %>% 
  unique()

bs_players <- bs %>% 
  select(player) %>% 
  unique()

bs_players <- bs_players %>% 
  mutate(check = ifelse(player %in% tagged_players$shooter,1,0))

bs_players_0 <- bs_players %>% 
  filter(check == 0)
```

```{r}
test1 <- shooter_ppg10 %>% 
  select(-team_code) %>% 
  right_join(matchups_filt1, by = c('game_id', 'player' = 'shooter')) %>% 
  mutate(pts_oe = pts - ppg_prev10)

lm1 <- lm(pts_oe ~ w_diff_gap, test1)

```

```{r}
test2 <- test1 %>% 
  filter(w_sum > 150)

lm2 <- lm(pts_oe ~ w_diff_gap, test2)
```

```{r}
test1 <- test1 %>% 
  mutate(tp = ifelse((pts_oe > 0) & (w_diff_gap > 0),1,0),
         tn = ifelse((pts_oe < 0) & (w_diff_gap < 0),1,0),
         fp = ifelse((pts_oe < 0) & (w_diff_gap > 0),1,0),
         fn = ifelse((pts_oe > 0) & (w_diff_gap < 0),1,0))
         

```

